"use-client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: allow side-effect CSS import without type declarations
import "./globals.css";
import Image from "next/image";
import { SunMoon } from "lucide-react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// library.add(duotone);
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<div className="min-h-[98vh]">
					<header className="relative flex justify-between items-center shadow-md p-4 overflow-hidden text-white">
						<div className="top-0 right-0 bottom-0 left-0 -z-1 absolute bg-linear-to-r from-secondary-500 to-primary-400 opacity-30 container"></div>
						<div className="top-0 right-0 bottom-0 left-0 -z-10 absolute bg-linear-to-r from-secondary-500 to-primary-400"></div>
						<div className="flex">
							<Image
								src="/nx-light.png"
								alt="Next.js logo"
								width={60}
								height={20}
							/>
							<h1 className="font-semibold text-2xl tracking-tight">
								UpGo <span className="text-transparent">NX</span>{" "}
							</h1>
						</div>
						<div className="flex justify-center items-center gap-5">
							<nav className="space-x-4">
								<a href="#" className="hover:underline">
									Home
								</a>
								<a href="#" className="hover:underline">
									Projects
								</a>
								<a href="#" className="hover:underline">
									Settings
								</a>
							</nav>
							<button className="right-2 bottom-2 sticky px-3 py-1 rounded-md">
								<SunMoon />
							</button>
						</div>
					</header>
					{children}
				</div>
			</body>
		</html>
	);
}
