import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: allow side-effect CSS import without type declarations
import "@/app/globals.css";
import { Providers } from "../providers";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ToastProvider } from "@heroui/toast";
import Header from "@/components/header";
import { ScrollShadow } from "@heroui/react";
import ScrollProvider from "./scroll-provider";
import SideBar from "./side-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UPGO NX",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  overflow-y-hidden `}>
        <Providers>
          <Header />
          <div className="bg-stone-200 dark:bg-stone-900 h-screen">
            <ToastProvider />
            <main className="grid grid-cols-20">
              <SideBar />
              <div className="col-span-20 md:col-span-17 bg-white dark:bg-black m-2 rounded-2xl overflow-hidden">
                <ScrollProvider className="p-2 h-[calc(100vh-7rem)]">
                  {children}
                </ScrollProvider>
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
